global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'task-demo'
    metrics_path: /actuator/prometheus
    static_configs:
      # my local IP address
      - targets: ['147.251.18.156:8080']
