spring:
  datasource:
    url: jdbc:postgresql://prospero-c.dis.ics.muni.cz:5432/inet2
    username: barca
    password: lepsieheslo
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics