{
 "title": "Times",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Time ScheduleGroup",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tREPLACE(st.clazz_path, 'com.example.taskdemo.tasks.schedules.', '') AS class_name, \r\n\tEXTRACT(epoch FROM (finish_date_time - start_date_time)) AS duration_s,\r\n\tfinish_date_time\r\n\t\r\nFROM task_log tl\r\nJOIN schedule_task st ON st.id = tl.schedule_task_id\r\nWHERE schedule_task_id IS NOT NULL\r\nAND finish_date_time IS NOT NULL AND $__timeFilter(finish_date_time)\r\nORDER BY class_name, finish_date_time;"
    }
   ]
  },
  {
   "title": "Time DaemonGroup",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tREPLACE(dt.clazz_path, 'com.example.taskdemo.tasks.daemons.', '') AS class_name, \r\n\tEXTRACT(epoch FROM (finish_date_time - start_date_time)) AS duration_s,\r\n\tfinish_date_time\r\n\t\r\nFROM task_log tl\r\nJOIN daemon_task dt ON dt.id = tl.daemon_task_id\r\nWHERE daemon_task_id IS NOT NULL\r\nAND finish_date_time IS NOT NULL AND $__timeFilter(finish_date_time)\r\nORDER BY class_name, finish_date_time;"
    }
   ]
  },
  {
   "title": "Time QueueGroup",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tREPLACE((qt.clazz::json->'type')::TEXT, 'com.example.taskdemo.tasks.queues.', '') AS class_name,\r\n\tEXTRACT(epoch FROM (finish_date_time - start_date_time)) AS duration_s,\r\n\tfinish_date_time\r\n\t\r\nFROM task_log tl\r\nJOIN queue_task qt ON qt.id = tl.queue_task_id\r\nWHERE queue_task_id IS NOT NULL\r\nAND finish_date_time IS NOT NULL AND $__timeFilter(finish_date_time)\r\nORDER BY clazz, finish_date_time;"
    }
   ]
  }
 ]
}