{
 "title": "Total tasks",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total schedule tasks by class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasks_run_total{group=\"ScheduleGroup\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total queue tasks by class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasks_run_total{group=\"QueueGroup\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total tasks by group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(group) (tasks_run_total{group=\"QueueGroup\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(group) (tasks_run_total{group=\"DaemonGroup\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(group) (tasks_run_total{group=\"ScheduleGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total daemon tasks by class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasks_run_total{group=\"DaemonGroup\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}