global:
  scrape_interval: 1s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'task-framework'
    metrics_path: /actuator/prometheus
    static_configs:
      # my local IP address
      - targets: ['host.docker.internal:8080']