{
 "title": "Durations",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Duration ScheduleGroup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tasks_run_total{group=\"ScheduleGroup\"} - ((tasks_finish_total{group=\"ScheduleGroup\"} offset -1s or tasks_run_total{group=\"ScheduleGroup\"} * 0) + (tasks_error_total{group=\"ScheduleGroup\"} offset -1s or tasks_run_total{group=\"ScheduleGroup\"} * 0)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration DaemonGroup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tasks_run_total{group=\"DaemonGroup\"} - ((tasks_finish_total{group=\"DaemonGroup\"} offset -1s or tasks_run_total{group=\"DaemonGroup\"} * 0) + (tasks_error_total{group=\"DaemonGroup\"} offset -1s or tasks_run_total{group=\"DaemonGroup\"} * 0))  > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration QueueGroup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tasks_run_total{group=\"QueueGroup\"} - ((tasks_finish_total{group=\"QueueGroup\"} offset -1s or tasks_run_total{group=\"QueueGroup\"} * 0) + (tasks_error_total{group=\"QueueGroup\"} offset -1s or tasks_run_total{group=\"QueueGroup\"} * 0)) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}