{
 "title": "Errors and successes",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ScheduleGroup errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(class) (tasks_error_total{group=\"ScheduleGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonGroup errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(class) (tasks_error_total{group=\"DaemonGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScheduleGroup successes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(class) (tasks_finish_total{group=\"ScheduleGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonGroup successes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(class) (tasks_finish_total{group=\"DaemonGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QueueGroup errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(class) (tasks_error_total{group=\"QueueGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QueueGroup successes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by(class) (tasks_finish_total{group=\"QueueGroup\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}